const  data=[{"id":6,
"name":"iPhone 12",
"description":"Kogi skateboard tattooed, whatever portland fingerstache coloring book mlkshk leggings flannel dreamcatcher.",
"imageUrl":"http://www.icentar.me/wp-content/uploads/2020/10/m4-iphone12.png",
"price":799}
,{"id":1,
"name":"iPhone 13",
"description":"Kogi skateboard tattooed, whatever portland fingerstache coloring book mlkshk leggings flannel dreamcatcher.",
"imageUrl":"http://www.icentar.me/wp-content/uploads/2021/10/m21-iphone13.png",
"price":349},
{"id":2,
"name":"Iphone 13 mini",
"description":"Kogi skateboard tattooed, whatever portland fingerstache coloring book mlkshk leggings flannel dreamcatcher.",
"imageUrl":"http://www.icentar.me/wp-content/uploads/2021/10/m21-iphone13mini.png",
"price":1499},
{"id":3,
"name":"Macbook Air",
"description":"Kogi skateboard tattooed, whatever portland fingerstache coloring book mlkshk leggings flannel dreamcatcher.",
"imageUrl":"http://www.icentar.me/wp-content/uploads/2020/11/mm2020-300-mba.png",
"price":999},
{"id":4,
"name":"Macbook Pro",
"description":"Kogi skateboard tattooed, whatever portland fingerstache coloring book mlkshk leggings flannel dreamcatcher.",
"imageUrl":"http://www.icentar.me/wp-content/uploads/2020/11/mm2020-300-mbp.png",
"price":599},
{"id":5,
"name":"Apple Watch Series 3 GPS",
"description":"Kogi skateboard tattooed, whatever portland fingerstache coloring book mlkshk leggings flannel dreamcatcher.",
"imageUrl":"http://www.icentar.me/wp-content/uploads/2021/10/m2021-watch3.png",
"price":499}]

export default data;